################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Program/Gecko\ SDK/platform/emlib/src/em_burtc.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_cmu.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_core.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_emu.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_gpio.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_iadc.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_ldma.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_msc.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_rtcc.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_system.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_timer.c \
D:/Program/Gecko\ SDK/platform/emlib/src/em_usart.c 

OBJS += \
./gecko_sdk_4.2.6/platform/emlib/src/em_burtc.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_cmu.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_core.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_emu.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_gpio.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_iadc.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_ldma.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_msc.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_rtcc.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_system.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_timer.o \
./gecko_sdk_4.2.6/platform/emlib/src/em_usart.o 

C_DEPS += \
./gecko_sdk_4.2.6/platform/emlib/src/em_burtc.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_cmu.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_core.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_emu.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_gpio.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_iadc.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_ldma.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_msc.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_rtcc.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_system.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_timer.d \
./gecko_sdk_4.2.6/platform/emlib/src/em_usart.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.2.6/platform/emlib/src/em_burtc.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_burtc.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_burtc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_cmu.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_cmu.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_cmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_core.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_core.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_emu.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_emu.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_emu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_gpio.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_gpio.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_iadc.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_iadc.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_iadc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_ldma.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_ldma.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_ldma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_msc.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_msc.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_msc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_rtcc.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_rtcc.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_rtcc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_system.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_system.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_system.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_timer.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_timer.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.6/platform/emlib/src/em_usart.o: D:/Program/Gecko\ SDK/platform/emlib/src/em_usart.c gecko_sdk_4.2.6/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\config" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP\autogen" -I"C:\Users\tuana\SimplicityStudio\v5_workspace\FCTSUMMERCAMP" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/thirdparty/mikrosdk_click_v2/clicks/co/lib/include" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/public/mikroe/co_mq7/inc" -I"D:/Program/Gecko SDK//extension/third_party_hw_drivers_extension-master/driver/peripheral_drivers/mikroe/inc" -I"D:/Program/Gecko SDK//platform/Device/SiliconLabs/BGM22/Include" -I"D:/Program/Gecko SDK//app/common/util/app_log" -I"D:/Program/Gecko SDK//platform/common/inc" -I"D:/Program/Gecko SDK//hardware/board/inc" -I"D:/Program/Gecko SDK//platform/driver/button/inc" -I"D:/Program/Gecko SDK//platform/CMSIS/Core/Include" -I"D:/Program/Gecko SDK//platform/service/device_init/inc" -I"D:/Program/Gecko SDK//platform/emdrv/dmadrv/inc" -I"D:/Program/Gecko SDK//platform/emdrv/common/inc" -I"D:/Program/Gecko SDK//platform/emlib/inc" -I"D:/Program/Gecko SDK//platform/emdrv/gpiointerrupt/inc" -I"D:/Program/Gecko SDK//platform/service/iostream/inc" -I"D:/Program/Gecko SDK//platform/driver/leddrv/inc" -I"D:/Program/Gecko SDK//platform/common/toolchain/inc" -I"D:/Program/Gecko SDK//platform/service/system/inc" -I"D:/Program/Gecko SDK//platform/service/sleeptimer/inc" -I"D:/Program/Gecko SDK//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.6/platform/emlib/src/em_usart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


